### ISSUE TITLE
[Bug]: A free 7th drone ;-) at Cold Metal

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2424] opened 2023-10-26 13:38 UTC
### What happened?

Operation Cold Metal: The previously lost drones are relaunched in C28. However, there is a 7th drone.  You can hopefully reproduce this with the attached file as well. 
[7 drones.zip](https://github.com/naev/naev/files/13178162/7.drones.zip)

![Screenshot_20231026_152847](https://github.com/naev/naev/assets/122737685/33d5cfd8-2daa-4954-a6e9-7d3e4e028c19)

**Comment by BM-W1** [comment] 2023-10-26 14:21
The 7th drone does no longer turn up after the end of the mission.

**Comment by bobbens** [comment] 2023-10-28 10:30
I can't reproduce. So the issue is you are somehow getting a 7th drone when you should only have 6 right?

**Comment by BM-W1** [comment] 2023-10-28 15:24
Yes. I could reproduce with the above snapshot. 
This is how it worked:
1. Let some of your drones be killed in Fortitiude. Relaunch, if possible. 
2. Fly to Hades. Some more of your drones killed. Relaunch, if possible.
3. Fly to C-59. Relaunch. There are no enemies. A while after having relauched 6 drones a 7th one is in the bay and can be launched. See here:
![Screenshot_20231028_172216](https://github.com/naev/naev/assets/122737685/d2161139-ec1c-44f2-9f11-730b756752d6)

**Comment by BM-W1** [comment] 2023-10-28 18:32
Some more observations:
1. The marker in C28 does not disappear after having entered C-00.
![Screenshot_20231028_173654](https://github.com/naev/naev/assets/122737685/06226d70-0588-49c2-b2eb-4d94fdf9b961)

2. I just waited with the 7 drones until the Starfire was destroyed.
![Screenshot_20231028_173736](https://github.com/naev/naev/assets/122737685/828a2e54-4b40-4b74-9727-5c64fa1cdd5f)

3. After having lost the 7th drone on the way back in Hades it did not turn up any more.

This is the savefile after landing in Fortitude.
[7 drones - the day after.zip](https://github.com/naev/naev/files/13196490/7.drones.-.the.day.after.zip)

Hope, this info may help finding the bug.

**Comment by BM-W1** [comment] 2023-11-04 21:49
When I was in Carrza and lauching a drone just for fun, I cannot give the return command after a while, because the drone bay is completely full. That means on the other hand that this is another case of 7 drones.
![Screenshot_20231104_224812](https://github.com/naev/naev/assets/122737685/7d114c3e-1545-4e6f-ad18-2225a967860d)

**Comment by bobbens** [comment] 2024-04-17 17:25
Finally found the issue. Was quite tricky, the newly launched escorts could start without an ID causing bsearch to fail and clear their launching pilot information. Should be fixed in next nightly, thanks!

**Closed by bobbens** 2024-04-17 17:25 UTC
Labels: Type-Defect
