### ISSUE TITLE
[Bug]: Reputation in  empire and dvaer

### ISSUE THREAD

**Issue by gerardchab** [naev/naev#2701] opened 2024-12-27 18:36 UTC
### What happened?

A bug happened! can't increase the reputation in dvaer or empire or not found the way to increase those! and can't buy peacemaker or dvaer goddart vessels.  for avance many thanks for your marvelous buiseness in this game G; Chab

### Version

naev 12.1

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MrTulias** [comment] 2024-12-27 19:12
Hi
Reputation is earned through faction quests.
If the problem is that you do not reach the available reputation, it may be due to the new reputation assignment, which is more localized. You may have achieved reputation in some areas and not in others, check the map and look at the reputation in the different systems.

**Comment by bobbens** [comment] 2024-12-30 08:36
Upon completing all available missions for a faction, you should get exactly 70% reputation standing. Some factions don't have campaigns which is why you start at 70%. As MrTulias mentions, you just have to do more content to increase the cap.

Closing as not a bug.

**Closed by bobbens** 2024-12-30 08:36 UTC
Labels: Type-Defect
