### ISSUE TITLE
Typos and other string issues

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1164] opened 2020-07-21 22:24 UTC
List of typos and other string problems I found:

----

* Not enough imput argument for asteroidpos
    * imput

* You are missing the %d tonnes of %s!.
    * !.

* Return to the %s system and deliver to Dr.Geller on %s
    * Dr.Geller → Dr. Geller

* "So the FLF is dead, I see. Well, not so much dead as a shadow of its former self. I can see that you did manage to more or less achieve your goal; Dvaered forces have largely withdrawn from Frontier space. I suppose that was the double-edged sword you wielded when you got pirates involved. The Empire was never going to allow you to live once you did that, but it did give you the edge you needed to weaken the Dvaered forces temporarily. [...]
    * Missing closing quotation mark at end of paragraph, or pointless opening quotation mark at beginning of paragraph.

* "I'm sure you're wondering who we are. We are the Thurion, a superior people and one of the Empire's former secret projects. Have you met the Za'lek? The Collective? Those too were the Empire's "great projects", as were the now dead Proteron. But we were kept a lot more in the dark. [...]
    * Same.

* "Now, most of us are uploaded, myself included. This face you see and this voice you hear are but projections, a reflection of myself that I have freely chosen. Being uploaded is wonderful, I must [...]
   * Same.

* "Greetings, %s," the pilot of the Vendetta says. "Sorry to bother you; I've just noticed that it's been quite some time since we contacted you and I wanted to check in on you. [...]
    * Same.

* "Unfortunately, news of this artifact has reached more ears than just mine. All over the galaxy there are people who will try to sell you 'ancient artifacts', which always turn out to be imitations at best and worthless scrap they picked up from the streets at worst." The Baron snorts derisively. [...]
    * Same.

* "Hello! I am here to claim my place as this cycle's champion! I've prepared myself since the first day I piloted a ship. Trust me, I'm nearly invincible and my Vendetta is indestructible. [...]
    * Same.

* "I am here to claim my place as this cycle's champion! I've prepared myself since the first day I piloted a ship. Trust me, I'm nearly invincible and my Vendetta is indestructible. [...]
    * Same.

* Baron Dovai Sauterfeldt turns the skate-board over in his hands, inspecting every nick, every scratch on the surface. His eyes are gleaming with delight. [...]
    * Same.

* "My General has just retired from the High Command and is now looking to become the Warlord of a planetary system. Unfortunately, our loyal forces do not seem sufficient enough to take on any existing planetary defense forces head on. [...]
    * Same.

* "You need to jump to each of the systems indicated on your map, and stay in the system until the scan finishes. If you jump out prematurely, you'll have to restart the scan from scratch when you return. [...]
    * Same.

* "I see. In that case, I'm going to have to ask you to leave. My job is to recruit a civilian, but you're clearly not the man I'm looking for. You may excuse yourself, citizen."
    * Player is explicitly male here.

* All right men, this will be Hawk's maiden jump. Continue on course to the %s jump gate.
    * Same.

* "I was in charge of a bombing run last week. The mission was a success, but I lost a lot of comrades. Oh well... this is the sacrifice we must make to resist the oppressors."
    * week?

* "This week Collective activity has increased heavily. We've been trying to contain them, but a scout broke through to the jump point. It was last detected by a patrol in %s, which saw it jumping out to %s. You are to locate the scout and report back to %s in the %s system. It seems like the Collective is planning something and we want to follow their game a little closer."
    "It is of vital importance that you do not engage the drone. Report back as soon as you locate it."
    * Same.

* Lieutenant Czesc from the Empire Aramda Shipping Division is sitting at the bar.
    * Aramda?

**Comment by Wuzzy2** [comment] 2020-07-21 22:27
More:

----

* "Hello there," he begins to speak, "I'm sure you have quite a few questions. My name is Shaman and I am a proud  commander in what is known as the Nasin. We are currently terrorize the Sirius overlords that control %s
    * double space (after “proud”, grammar
* Your not sure exactly what to expect, but you think that they've been expecting you.
    * grammar
* Your payment of %s was credited  to your account.
    * double space (after “credited”)
* [...] My sincerest apologies for being absent. [...]
    * Has opening quotation mark at start, but no closing quotation mark at the end
* [...] I hope its good enough"
    * Missing period at end. Also, “its”?
* At this, he runs off to helps a group of elderly citizens who are struggling against the tide of people.
    * helps → help

**Comment by PhoenixRiver** [comment] 2020-07-24 02:33
Hiya :)

Good catch on the speech mark thing... I think it is because if there
is non-speech in the text shown that the speech marks are needed but
they are not need if the text only contains speech. These all need to
be fixed for things to be consistent unless we want to change the
standard, in which case there are a lot more others that need fixed...

> * Your not sure exactly what to expect, but you think that they've been
> expecting you.

>     * grammar

Should be something like "You're not sure what might be about to
happen exactly but you think they've been expecting you."
 - removes the doube use of the word "expect" which is bad as well as
moving the "exactly" to the correct place and fixing the incorrect use
of "your".

> * Your payment of %s was credited  to your account.

>     * double space (after “credited”)

Also "The payment" would be better due to the bad double use of "your"
in the same sentence.

> * [...] My sincerest apologies for being absent. [...]

>     * Has opening quotation mark at start, but no closing quotation mark at
> the end

> * [...] I hope its good enough"

>     * Missing period at end. Also, “its”?

"its" should be "it's", yes :)

I agree with all of the other corrections :)

Hope this helps,

River

**Comment by onpon4** [comment] 2020-07-27 23:46
Going through and fixing things. Just a note:

> Missing closing quotation mark at end of paragraph, or pointless opening quotation mark at beginning of paragraph.

That's actually on purpose and matches quotation styling for English text. There's no closing quote because the quote continues on the next paragraph.

**Comment by onpon4** [comment] 2020-07-27 23:59
Alright, I've fixed the legitimate ones in #1175. Like I said, the trailing unclosed quotes are by design, it indicates that the quote is continuing onto the next paragraph. Also all the issues you pointed out in the second post are outdated, those quotes only seem to exist in comments on the German translation file on my end.

🕷️

**Closed** 2020-07-28 00:31 UTC
