### ISSUE TITLE
Split monolithic files to support modding

### ISSUE THREAD

**Issue by UncombedCoconut** [naev/naev#1646] opened 2021-01-08 16:46 UTC
We have a few singleton files (faction.xml, spfx.xml, ...), so Naev mods (implemented as PhysicsFS overlay mounts) can only extend them by completely shadowing them.
Most of these can be split into directories; then mods could add content in new files.

**Comment by bobbens** [comment] 2022-02-03 12:35
I guess #1707 is a duplicate of this, but since it has the files listed and is tracking development a bit more, I'm going to go ahead and close this issue.

**Closed by bobbens** 2022-02-03 12:35 UTC
Labels: Type-Enhancement, Priority-Low, GoodFirstProject
