### ISSUE TITLE
[Bug]: Friendly factions ignore stealth

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2470] opened 2023-12-04 18:32 UTC
### What happened?

Sirius +70% and Sirius ships are ignoring my stealth. please see attached snapshot.
[stealth ignored.zip](https://github.com/naev/naev/files/13550001/stealth.ignored.zip)
![Screenshot_20231204_193142](https://github.com/naev/naev/assets/122737685/b8c12c74-a1ec-4fba-8b50-c667869796ba)

### Version

0.11.0 beta-1+24 (current)

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by not-pyroman** [comment] 2023-12-04 19:03
I do believe that is intentional, since when you're Friendly with a faction, they are considered allies with you and if I understand correctly shouldn't scan you either, and it wouldn't make much sense if a ship that's allies with you also uncovers you if you're allied with a pirate clan for example

**Comment by bobbens** [comment] 2023-12-05 02:46
If the issue is friendly ships seeing through your stealth and not destealthing you. That's a feature, just like how your escorts do it.

**Comment by not-pyroman** [comment] 2023-12-05 14:27
I think it should be safe to close this, just some confusion from people not really encountering factions liking you enough to be friendly/allies until now.

**Closed** 2023-12-05 15:26 UTC
Labels: Type-Defect
