### ISSUE TITLE
[Bug]: no drones launch (beta3 only)

### ISSUE THREAD

**Issue by BM-W1** [naev/naev#2487] opened 2023-12-14 15:04 UTC
### What happened?

Drones cannot be launched in beta 3. Lauch works well in beta2+100.

### Version

0.11.0 beta-3

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by bobbens** [comment] 2023-12-14 15:11
OK. So the issue is with weapon sets that have 'in range' checks. It's not an issue with toggle weapon sets. Either way, I've pushed a fix and am doing a stealth update of v0.11.0-beta.3 that should be live in 30ish minutes. Thanks!

**Closed by bobbens** 2023-12-14 15:11 UTC
Labels: Type-Defect
