### ISSUE TITLE
Clearing U/S slots after upgrade

### ISSUE THREAD

**Issue by exa18** [naev/naev#1708] opened 2021-02-25 09:53 UTC
After upgrade from 0.8.0 to 0.8.2+dev
My ships have cleared utility and support slots.
They seems empty (no icons, and show as empty when comes to install new one) but limits cpu/mass have level like equipment still there.
Here you have my save and conf: https://github.com/naev/naev/issues/1706#issuecomment-783974549

**Comment by onpon4** [comment] 2021-02-25 15:57
This is a duplicate of #1706 is it not? I just opened the save and the problem is your weapons configuration, as with Instant Mode as mentioned in the other issue. Enable automatic handling of weapons and it sets the afterburner to slot 9 automatically and can be used no problem. As with Instant Mode manual configuration isn't explained, so that needs to be addressed, but this is the same problem in the case of both how Instant Mode works and how assigning activated outfits works. Given that, let's discuss potential solutions to this documentation problem in #1706 (and in your case, I would for now recommend leaving automatic handling of weapons enabled as this solves both of the problems you're facing attempting to manually configure).

Closing this as it is a duplicate of #1706.

🕵️

**Closed by onpon4** 2021-02-25 15:57 UTC
