### ISSUE TITLE
Fake transponder activates after removal

### ISSUE THREAD

**Issue by amylaar** [naev/naev#2091] opened 2022-02-23 07:13 UTC
When I remove the transponder, then quit the game and load (esc-x-l-l), the transponder standing values are active again, and won't
go away anymore.
[wild--22.ns.gz](https://github.com/naev/naev/files/8122487/wild--22.ns.gz)

**Comment by PhoenixRiver** [comment] 2022-02-24 11:34
I can make a pull to fix all of these fake transponder issues we've had since it was introduced... but given that I'd just be removing it from the game and I'm not sure that would be liked I'll not take the time to code it up... particularly since I don't have grep on my system and so finding all the places it is referenced would be an issue - never mind making sure there was code to handle all the save files with it in... *sigh*

**Comment by amylaar** [comment] 2022-02-24 12:23
The fake transponder replaced the fake id - you pretty much need at least one of them to make the FLF mission feasible.

I think the basic problem of having potential for such impactful bugs is that both fakes are patching global variables.
A cleaner - but more laborious to implement - solution would be to keep the permanent standing always in the same place, and have an actual alternate identity for the 'regular' factions.  You'd have something that point at the current effective identity for the 'regular' factions, and make stuff that's supposed to use or query its values refer to the fake identity.
That's also actually making the code more closely model what the game reality is supposed to be.

**Comment by bobbens** [comment] 2022-02-25 02:33
Thanks for the save, I can reproduce.

**Comment by bobbens** [comment] 2022-02-25 03:32
Should be fixed in main, thanks!

**Closed by bobbens** 2022-02-25 03:32 UTC
