### ISSUE TITLE
trail.frag causes horrible performance in Point of Interest missions

### ISSUE THREAD

**Issue by Ytrog** [naev/naev#2364] opened 2023-08-07 13:41 UTC
I had slide-show like performance everytime the trail fragment shader was on screen. I was looking into the cause of it and it seems it is the perlin noise generation.

When I changed the iterations in the following line from 2 to 0 the game ran on a normal framerate and I could complete the mission in minutes instead of hours:
https://github.com/naev/naev/blob/f94d1da4c3ab81d61e2a3ead3afa1c864f5bb78c/dat/scripts/luaspfx/shaders/trail.frag#L3C26-L3C26

My laptop specs are:
- HP Envy 4
- 4GB RAM
- Intel HD Graphics 3000

So yeah it is definitely a potato, however this might help other potato-owners that have this issue.

**Comment by bobbens** [comment] 2023-08-07 14:05
What version are you running? And what OS are you on?

**Comment by Ytrog** [comment] 2023-08-07 16:15
It is `0.10.6` on Windows 7

**Comment by bobbens** [comment] 2023-08-08 02:38
I'm a bit confused because `dat/scripts/luaspfx/shaders/trail.frag` is actually not used. It's from an older implementation of the trails that has crept in. That said, 0.10.6 fixed a memory leak in the trails, but it seems like you're on that version already.
Can you describe exactly when it slows down? Could it be when you start the minigame? If so, you might want to try https://github.com/naev/simple-shaders-plugin which disables the circuit shader and fixed a slowdown issue on mac os.

**Comment by Ytrog** [comment] 2023-08-08 08:13
It is when the trail you have to follow is on screen. Those colored blocks.

**Comment by bobbens** [comment] 2023-08-08 12:11
Are there any other times you have slowdowns? Just to double check that it's the spfx, does the following line cause the slowdown if you type it in the console (F2)?
```lua
require("luaspfx.trail")( player.pos() )
```

**Comment by Ytrog** [comment] 2023-08-10 21:04
I will do so later as I'm now on a holiday abroad.

**Comment by bobbens** [comment] 2023-10-01 06:05
Any update on this?

**Comment by Ytrog** [comment] 2023-10-07 10:12
Not yet. If forgot. 🫣

**Comment by bobbens** [comment] 2023-11-08 05:08
Is this still an issue? If not I'll be closing before we release 0.11.0.

**Comment by Ytrog** [comment] 2024-03-25 13:25
Close it. I am not able to follow up on it currently and I don't want to hold you up.

**Comment by ProjectSynchro** [comment] 2024-06-18 02:13
Closing this as it seems like the issue was resolved / the issue is stale, let us know if you run into this issue with any newer releases :)

**Closed by ProjectSynchro** 2024-06-18 02:13 UTC
