### ISSUE TITLE
Crash after loading

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1627] opened 2021-01-03 04:08 UTC
I've started the FLF campaign and tried to get some positive Dvaered reputation by helping them with the pirates so they
might tolerate my interfering with their patrols, but at some point it crashes when I try to depart from the planet - or even just
try to exit the game after loading.  there seems to be some kind of memory corruption.

**Comment by amylaar** [comment] 2021-01-03 04:51
I meant to attach the save file, but I can't figure out how to do that - maybe it works only for videos and special Microsoft formats?  I click an the thing that says attach files, a file selector comes up, I enter the file name, type open, and nothing happens.  I search around for a file manager, drag & drop the file, and depending where I put that, either the local filename gets inserted into the comment, I get offered to 'save' the file, or nothing happens.
I also tried pasting all 8710 lines of the uncompressed safe file, but then the comment just vanished.  Should I provide the file by email / ftp / git checkin ?

**Comment by amylaar** [comment] 2021-01-03 05:01
[Zora.ns.gz](https://github.com/naev/naev/files/5761225/Zora.ns.gz)

Hmm, tried from another computer with a newer browser, and this time I get told what file 'types' (actually, file name extensions) are accepted.  .ns is not included, but .gz is.  So I gzipped the save file (which was already gzipped, but not thus named..) giving a slightly larger double-gzipped file.

**Comment by UncombedCoconut** [comment] 2021-01-03 08:16
That's odd. Nothing in this save looks like it should crash -- and, when I load it into Naev (0.8.1 pre-release or master) it doesn't do anything suspicious. What Naev version (number, OS, distribution like Steam if applicable) are you using?

**Comment by amylaar** [comment] 2021-01-05 03:23
naev-0.8.0-linux-x86-64.AppImage as downloaded.  (md5sum for that file is c6e16a055aa319f1a781d9af67d1e6f4 ; uname says: Linux localhost.localdomain 5.9.16-200.fc33.x86_64 #1 SMP Mon Dec 21 14:08:22 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux )

I also tried copying the save file to anther laptop with a different display size and more memory, and it crashed just the same.  Curiously, the backup file also crashed, but I found that if I started a new game first, deselected big icons, then loaded the backup file, I could continue without crashing.  Not with the main savefile above, though.

I just double-checked that I can reproduce the crash - and I couldn't!  I applied some OS updates changed the window manager in the meantime, and I think I had naev full-screen before but now it's in a window when it starts, so I first wondered if that might have changed things.
I went then back to an earlier file that also crashed, but as I believed back then a bit more finicky to trigger - after loading, I typed 'm' tp get the map, selected the destination PSO with the touchpad, hit autonav,
and then takeoff  .  The savefile copy for that is is Zora.ns.crash-on-departure . 
[crashes.tar.gz](https://github.com/naev/naev/files/5767902/crashes.tar.gz)
A bit more testing with this file, the newer save file (as attached before) and its backup (included in the tar.gz) leads me to believe
that the crashes happen now more like 60% of the time.  Maybe address space randomization confuses the issue?  The
output also varies a bit, I've included that cut&pasted in 'output' in the tar.gz .  I hope attaching works this time, I first couldn't
input the path name as the file selector wouldn't allow me to input the .local pathname component, and then when I made a symlink, it wanted to attach the link as such .  I made a copy and now the name and what I assume is the remote pathname on github are shown somewhat weirdly inside the comment,

**Comment by UncombedCoconut** [comment] 2021-01-06 04:59
Hi, @onpon4 helped investigate and was able to reproduce the crash -- specifically, when it's reproducible in the 0.8.0 AppImage release.
Other Naev builds tried so far *don't* show the problem, including nightly AppImages. This isn't a recommended as a fix, since games saved from a nightly may become incompatible with official releases, but it's a sign that we may have fixed the underlying problem already.
Our plan at this point is to release Naev 0.8.1 Very Soon (tm) and re-test Zora.ns.gz there.

**Comment by amylaar** [comment] 2021-01-06 07:54
Here's another test case; I tried several times with loading something else first and changing big icons, set autonav to Ogat before takeoff or just takeoff just after load, but got crashes seven times out of seven.
[crash.tar.gz](https://github.com/naev/naev/files/5774502/crash.tar.gz)

**Comment by amylaar** [comment] 2021-01-06 22:11
Yet another test case:
[crash.tar.gz](https://github.com/naev/naev/files/5778382/crash.tar.gz)
This time, I downloaded today's nightly build to see if that'd work better.  It is worse, it crashes during loading.  And not only
for the main save file, but the backup too.  It also crashes when trying to start a new game.  I've tried to have a save folder
with only main save and backup file, and removing the cache, but to no avail - it still crashes trying to load a save file.  Or to start a new game.
This is on a machine that has 4 GB Ram and at a fresh Fedora 33 install, i.e. it lacks swap, so I wondered if the nightly build might just need more memory.
So I copied the files over to a laptop with 8 GB ram and 12 GB swap (fedora 33 upgraded from a close earlier version),
but still the nightly build crashes on loading or starting a new game.

**Comment by amylaar** [comment] 2021-01-07 06:39
Same with the the nightly build from today.  I tried strace with a run where I just click on 'exit', and it shows that it gets a SIGSEGV just after copying conf.lua to conf.lua.backup and writing a new conf.lua (last syscall is closing the file descriptor for that file).
0.8.0 goes on to call futex and a lot of ioctl DRM_IOCTL_I915_GEM_MADVISE on a file descriptor optained with fcntl F_DUPFD_CLOEXEC on another obtained opening /lib64/libxcb-xfixes.so.0 (I did the strace on that machine withe the larger RAM)

**Comment by amylaar** [comment] 2021-01-07 19:45
I tried building from git source - commit 7f3ed21b7cd46478e11052529e30862ee910315b - and also installed debug info.
This is the backtrace when I exit straight after starting naev (without loading):
(gdb) bt
#0  __memmove_avx_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:483
#1  0x000000000042a4ba in _array_erase_helper (a=<optimized out>,
    e_size=e_size@entry=4, first=<optimized out>, last=<optimized out>)
    at ../src/array.c:74
#2  0x0000000000457640 in faction_rmEnemy (f=f@entry=15, o=o@entry=8)
    at ../src/faction.c:498
#3  0x00000000004e1fe3 in diff_patchHunk (hunk=hunk@entry=0x7fffffffce60)
    at ../src/unidiff.c:860
#4  0x00000000004e39df in diff_removeDiff (diff=0x4af0d80)
    at ../src/unidiff.c:1047
#5  0x00000000004e4125 in diff_clear () at ../src/unidiff.c:943
#6  0x00000000004be361 in player_cleanup () at ../src/player.c:674
#7  0x000000000048e69e in unload_all () at ../src/naev.c:659
#8  0x000000000048ff29 in main (argc=<optimized out>, argv=<optimized out>)
    at ../src/naev.c:441

And this is the one for loading a game:

It seems like naev has crashed. Please debug with gdb now ;)
__memmove_avx_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:483
483		VMOVU	(%rsi), %VEC(0)
(gdb) bt
#0  __memmove_avx_unaligned_erms ()
    at ../sysdeps/x86_64/multiarch/memmove-vec-unaligned-erms.S:483
#1  0x000000000042a4ba in _array_erase_helper (a=<optimized out>, 
    e_size=e_size@entry=4, first=<optimized out>, last=<optimized out>)
    at ../src/array.c:74
#2  0x0000000000457640 in faction_rmEnemy (f=f@entry=15, o=o@entry=8)
    at ../src/faction.c:498
#3  0x00000000004e1fe3 in diff_patchHunk (hunk=hunk@entry=0x7fffffffcd00)
    at ../src/unidiff.c:860
#4  0x00000000004e39df in diff_removeDiff (diff=0x43e0280)
    at ../src/unidiff.c:1047
#5  0x00000000004e4125 in diff_clear () at ../src/unidiff.c:943
#6  0x00000000004be361 in player_cleanup () at ../src/player.c:674
#7  0x0000000000475720 in load_gameInternal (
    file=0x4b2e460 "e/joern/.local/share/naev/saves/Zora.ns", 
    version=0x4278420 "0") at ../src/load.c:620
#8  0x0000000000476359 in load_game (ns=ns@entry=0x33ac080)
    at ../src/load.c:587
#9  0x000000000047645f in load_menu_load (wdw=3, str=<optimized out>)
    at ../src/load.c:444
#10 0x00000000004e0fcb in toolkit_mouseEventWidget (w=w@entry=0x3495740, 
    wgt=wgt@entry=0x4142e40, event=event@entry=0x7fffffffcef0, 
    x=<optimized out>, y=18, rx=<optimized out>, ry=0) at ../src/toolkit.c:1800
#11 0x00000000004e10b1 in toolkit_mouseEvent (w=w@entry=0x3495740, 
    event=event@entry=0x7fffffffcef0) at ../src/toolkit.c:1686
#12 0x00000000004e14ef in toolkit_inputWindow (wdw=0x3495740, 
    event=event@entry=0x7fffffffcef0, purge=purge@entry=1)
    at ../src/toolkit.c:1586
#13 0x00000000004e1859 in toolkit_input (event=event@entry=0x7fffffffcef0)
    at ../src/toolkit.c:1549
#14 0x000000000046dc38 in input_handle (event=event@entry=0x7fffffffcef0)
    at ../src/input.c:1550
#15 0x000000000048fed2 in main (argc=<optimized out>, argv=<optimized out>)
    at ../src/naev.c:431

**Comment by amylaar** [comment] 2021-01-07 20:17
commit d87e14a06968824aebfc5d436a34eb5bc29a63d6 works.

commit a4abbb943f619c8e18c69e6733e6f86d030dfa47
Author: Edgar Simo-Serra <ess@waseda.jp>
Date:   Tue Jan 5 19:56:17 2021 +0900

    Made factions interally use arrays.

crashes.

**Comment by UncombedCoconut** [comment] 2021-01-08 05:15
There's a fix for the last crash (involving commit a4abbb9) now.
There's nothing I'd expect to have resolved the symptoms reported 1-2 days ago, though. (The nightly AppImage apparently doesn't feel like being naughty while I'm watching it. :-/)

**Comment by amylaar** [comment] 2021-01-08 07:44
I did another build with the latest git sources (top commit 08c944057fe93623ffa01 ... ) and it seems to work.

**Comment by amylaar** [comment] 2021-01-09 09:13
> Hi, @onpon4 helped investigate and was able to reproduce the crash -- specifically, when it's reproducible in the 0.8.0 AppImage release.
> Other Naev builds tried so far _don't_ show the problem, including nightly AppImages.

I've attempted a bit of interval search in git versions between 0.8.0 and the known working version.

218bc54ee9aa58be4e5c540502ec3b7f2a54bf1f
fails to build with:
../meson.build:128:6: ERROR: Mercurial program not found.

33ad0dd21683ff8a92204bdaddcba087af897edc
allows takeoff but crashes shortly after

8ffd8f3550248ba2fbda604b5fcff49cf3f3d7fc
Likewise - confirmed five times

a2460aa794327eeab58333cdf50ab34fb2a4130f
Seems to work - confirmed five times

44c9671100f4fc7a939244c93b54b1b857b024c6
c7e336ec663cb9e5cb6b34a9b8403df4ae00720d
meson compile says no work to do, coming from 4464eee38959a2814ac69ced9fd1a326ed219428

4464eee38959a2814ac69ced9fd1a326ed219428
Seems to work

2a38bc008e2cb52a69a622c3a1f5cbafa83aaa60
Seems to work

**Comment by bobbens** [comment] 2021-01-14 08:11
I believe this should be fixed in master, if not reopen please.

**Closed by bobbens** 2021-01-14 08:11 UTC
