### ISSUE TITLE
za'lek test engine remains and no soromid bioship leveling: rmOutfit at fault?

### ISSUE THREAD

**Issue by amylaar** [naev/naev#1626] opened 2021-01-03 00:20 UTC
I've found that at the end of a Za'lek engine test mission, I'm left with the test engine in my ship (worth 110K credits if I put it in a llama and sell the llama with the engine).
Also, the Soromid bioships don't level up even when I finish a mission worth more than one million credits (and why does experience not accumulate anyways?)
I've looked at the source and suspect pilotL_rmOutfit in nlua_pilot.c may be at fault.  The change from 8th December 
removed the ability to handle strings other that "all" or "core".

**Comment by onpon4** [comment] 2021-01-05 01:35
I believe this was fixed by 94b63d4051de10d46bfc254467e149fab9890b80. Closing this now on that assumption; please let us know if the problem is not solved for you.

🕵️

**Closed by onpon4** 2021-01-05 01:35 UTC
Labels: Priority-High, Type-Defect
