### ISSUE TITLE
[Bug]: reputation: in empire faction: youcan have a maximum reputation of 65% if i want to buy vessel empire peacemaker: you need at least 70% reputation with the empire???? a joke or a mistake? regards  G Chab

### ISSUE THREAD

**Issue by gerardchab** [naev/naev#2702] opened 2024-12-28 14:48 UTC
### What happened?

A bug happened!

### Version

naev 12.1

### What operating system are you seeing the problem on?

Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by HyperSoop** [comment] 2024-12-28 14:54
it's a skill issue if anything, you need to do more missions with them to raise the reputation cap

**Comment by bobbens** [comment] 2024-12-28 15:25
You will hit 70% if you complete all the available content. For the Empire this is:
* collective campaign
* long distance shipping campaign
* regular shipping

You are probably missing the collective campaign.

**Comment by HyperSoop** [comment] 2024-12-28 15:36
the collective campaign takes place in systems surrounding Omega Enclave, you should be able to pick up the storyline in its bar

**Comment by bobbens** [comment] 2024-12-30 08:35
Closing as not a bug.

**Closed by bobbens** 2024-12-30 08:35 UTC
Labels: Type-Defect
