### ISSUE TITLE
Naev installer fails to install correctly when using silent install

### ISSUE THREAD

**Issue by superusercode** [naev/naev#2335] opened 2023-05-20 23:48 UTC
![239113579-24fd0af0-135a-484e-8b64-8deddab6dc0c](https://github.com/naev/naev/assets/60588434/92097c82-67fa-46d8-9217-c06468baaa0a)
per https://github.com/microsoft/winget-pkgs/pull/106890

The silent switches on the installer are also semi-altered from the nullsoft defaults, which would have put it in program files and allowed for changing the directory silently.

**Comment by ProjectSynchro** [comment] 2023-05-21 01:12
As far as I am aware we don't do anything that would force the installer to install in any non-standard locations. 

We also make use of the standard [`$INSTDIR`](https://github.com/naev/naev/blob/8e55daec6b5593779ffdfd6c54079ecb43b582ef/extras/windows/installer_assets/naev.nsi#L97) variable when installing files, so I'm not really sure what's up here. 

Graphically installing the application places it in `C:/Program Files (x86)/Naev` by default as the installer is a 32-bit installer by default (this is due to the installer being compiled on a Linux VM, but shouldn't matter)
![image](https://github.com/naev/naev/assets/5131712/8bd01ce1-e603-44af-af80-ceaf601f7a4e)

As for how itch.io installs Naev properly, it is deployed there as a zipped archive and extracted by the itch.io app upon download.

I'll investigate further and attempt to reproduce issues with the silent install option, we might be missing default values for some of the variables NSIS expects to be set.

**Comment by ProjectSynchro** [comment] 2023-05-21 01:24
Can reproduce the issue with silent installs, appears to install files to the drive root of whatever drive the installer is located on.

Will need to look into what we need to change to fix this.

**Comment by ProjectSynchro** [comment] 2023-05-21 01:28
As a side-note, you can fix the bogus installer entry in Control Panel by reinstalling Naev 'for everybody' while using the graphical installer. The registry keys associated with the uninstaller do not appear to be set correctly using a silent install.

**Comment by ProjectSynchro** [comment] 2023-07-07 11:34
Silent install (/S flag) appears to be fixed as of: https://github.com/naev/naev/commit/8e4aec09662d43fe341d67483b0bd809b06eba9c

I'll re-open this if that appears to not be the case :sweat_smile:

**Closed by ProjectSynchro** 2023-07-07 11:34 UTC
Labels: OpSys-Windows, Priority-High

**Comment by ProjectSynchro** [comment] 2023-07-07 12:41
This fix is now available in https://github.com/naev/naev/releases/tag/v0.10.6
