### ISSUE TITLE
make fails on ITSTOOL when compiling Out-Of-Tree : cannot open XML file dat/commodity.xml

### ISSUE THREAD

**Issue by Mutos** [naev/naev#1148] opened 2020-07-11 14:58 UTC
Hi all,

I'm having another error about compiling, which is related to ITSTOOL :

`Making all in po
  LN    naev
Error: cannot open XML file dat/commodity.xml
Makefile:1102: recipe for target '../../po/xml.pot' failed
make[1]: *** [../../po/xml.pot] Error 1
Makefile:667: recipe for target 'all-recursive' failed
make: *** [all-recursive] Error 1`

instead of 

`Making all in po
  LN    naev
ITSTOOL po/xml.pot`

There must have something to do with adding xml files to the localization system. This in fact prompts two distinct issues in my way of working with NAEV for SoC :
- I must compile OOT, so I must find a dirty workaround similar to Issue #1147;
- SoC has a different ndata than NAEV, so I must find a way to compile ITSTOOL things using both NAEV and SoC ndata to be able to run both games from the folders structures I've devised...

**Comment by Mutos** [comment] 2020-07-11 15:08
Seems the idea should be to take dat from NAEV's root folder instead of compilation root folder. There must be somewhere a variable to reference that...

**Comment by bobbens** [comment] 2020-07-16 04:15
You have multiple options:
1. Disable with `--disable-nls` to disable all translation stuff
2. Edit the part in `Makefile.am` referring to the different xml files used (around line 40).
3. Add some checks to see if file exists and ignore them if they don't.

**Comment by bobbens** [comment] 2020-07-16 04:18
I have changed it to use wildcards in 2bdbe3029843b27a9352df00b72dfcfcd65d3799 , which doesn't seem to change anything, but shouldn't error out if it doesn't find the files.

**Comment by Mutos** [comment] 2020-07-16 08:27
Thnks @bobbens for the hint to edit `Makefile.am`, I'll look and try to understand this file's syntax and meaning. All I know for sure, is that it's where you declare which file you need for compiling... I'll keep you informed...

**Comment by Mutos** [comment] 2020-07-16 08:28
And btw, for now I compile by examining the missing files in the error messages and copying them by hand where they are needed.

**Comment by bobbens** [comment] 2020-07-16 09:22
Do you mean that the issue is not fixed with latest master?

**Comment by Mutos** [comment] 2020-07-16 10:00
Just got the latest master commit 791daa768, still doesn't work, complains on `dat/LANGUAGES`.

**Comment by Mutos** [comment] 2020-07-16 10:07
Trying `LANGUAGEFILE = $(wildcard dat/LANGUAGES)` in `Makefile.am`, don't know if wildcard will work if there is no aactual wildcard in the argument...

**Comment by Mutos** [comment] 2020-07-16 10:09
Seems not to work, trying with `LANGUAGEFILE = $(wildcard dat/LANGUAGES*)`...

**Comment by bobbens** [comment] 2020-07-16 10:20
Should be fixed in b7971a4172a0b03fa5feed612abe5925d3b28d29 .

**Comment by Mutos** [comment] 2020-07-16 10:41
Thanks a lot, this time it works !

I totally cleaned the repo and retried anew, it worked !

**Comment by Mutos** [comment] 2020-07-16 10:43
And as usual, I forgot to close the issue....

**Comment by onpon4** [comment] 2020-07-30 11:21
Closing since you said it's fixed.

**Closed by onpon4** 2020-07-30 11:21 UTC
