### ISSUE TITLE
naev.org down?

### ISSUE THREAD

**Issue by smeagolthellama** [naev/naev#825] opened 2019-05-09 11:25 UTC
I can't connect to [naev.org](naev.org). Is the problem between me and my ISP, or is the site down?

**Comment by BTAxis** [comment] 2019-05-09 11:31
The site is down.

**Comment by smeagolthellama** [comment] 2019-05-09 11:56
when is it expected to come back up?

**Comment by ids1024** [comment] 2019-05-09 17:50
Ping @Deiz

**Comment by Mutos** [comment] 2019-05-11 07:23
Still down for me.

**Comment by PhoenixRiver** [comment] 2019-05-12 08:18
Still down for me too (from Japan).

**Comment by Mutos** [comment] 2019-05-12 09:39
No news ? Still down for me, from France.

**Comment by BTAxis** [comment] 2019-05-12 09:43
The situation as far as I know is that Deiz manages the website, and he hasn't been around. I'm unsure if the website will be back anytime soon.

**Comment by fiendish** [comment] 2019-06-06 16:22
Could it be switched over to gh-pages?

**Comment by BTAxis** [comment] 2019-06-06 16:28
Hosting is not really the issue. The issue is that we don't have the data for the forums and such, so we can't really restore them.

**Comment by devastator-pc** [comment] 2019-06-26 13:59
Isn't there any way to contact Deiz? He seems to be quite active on other github repositories recently?

**Comment by jostephd** [comment] 2019-06-27 17:36
Right now http://www.naev.org/ gives a DNS error. That makes it look like the project is dead. Even if you don't have the data for the forums I would recommend to set up a temporary 404 page. A 404 page is not ideal but it's better than a DNS error page.

**Comment by Mutos** [comment] 2019-06-28 21:55
DNS error but the whois gives an expiration date of 2020, so it's not dropped. 404 page is a good idea. 1/ Where could it be redirected ? Steam ? Github ? Another domain ? 2/ Does anyone here has access to the hosting ?

**Comment by onpon4** [comment] 2019-08-02 01:30
So I just wanted to weigh in and say that honestly, loss of the forum is not that big of a deal. The only thing in particular I'd say needs to be restored is api.naev.org, and some kind of website (it doesn't need to be the same one) so that the project doesn't look dead.

**Comment by ids1024** [comment] 2019-08-02 02:01
> loss of the forum is not that big of a deal.

A lot of detailed proposals for story arcs and such were scattered around the forum; so that's one relevant loss.

> The only thing in particular I'd say needs to be restored is api.naev.org

https://naevdocs.ids1024.com/ has documentation that is automatically updated to match `master`. But yeah, it would be good to have it in the official location.

If someone in control of the DNS wants to point the `api` subdomain to my server, that would work (and I could adjust the configuration to serve there). I presume the traffic isn't too high even for my tiny VPS.

>  and some kind of website

Yeah. Having at least something is probably worthwhile.

**Comment by ids1024** [comment] 2019-08-02 02:29
As for what happened to the site, there was a mention on IRC in May: https://colabti.org/irclogger/irclogger_log/naev?date=2019-05-17

**Comment by bobbens** [comment] 2019-08-03 23:24
I tried e-mailing Deiz and got no reply. I don't have a backup nor access to the original server so I can't restore the data. Unless somehow Deiz wakes up I'm guessing we'll have to remake the site...

**Comment by Mutos** [comment] 2019-08-24 06:55
1/ Is it possible to get something back from the web archive ?
2/ I can propose a hosting on the same server as the one I use for [http://hoshikaze.net](http://hoshikaze.net) and a few other sites. I got plenty of disk space to spare. Of course, someone will have to install an up-to-date WordPress and populate it with some relevant content. This could begin with a simple presentation site redesign, then ramp up to restoring the forum and wiki once we got the data backups...

**Comment by tmoftdead** [comment] 2019-08-30 17:06
maybe we should use the wayback machine and copy the few ideas and still working wiki articles to another forum and/or direct it to a new site like the one before.

**Comment by bobbens** [comment] 2019-09-03 13:20
OK. Regarding backups, if there are any, only Deiz would have the knowledge of where there are. As he is still missing in action for quite a while, I think it is safe to assume that there is no backup.

> 1/ Is it possible to get something back from the web archive ?

Probably, but it is quite a lot of manual work.

> 2/ I can propose a hosting at Ouvaton on my own account, which I use for http://hoshikaze.net and a few other sites. I got plenty of disk space to spare. Of course, someone will have to install an up-to-date WordPress and populate it with some relevant content. This could begin with a simple presentation site redesign, then ramp up to restoring the forum and wiki once we got the data backups...

For a simple site, I would suggest using [github pages](https://pages.github.com/), which should work for static html.  Something like [jekyll](https://jekyllrb.com/) or [nanoc](https://nanoc.ws/) can be used to generate the html. However, forum/wiki would not be possible. I have activated the wiki on github so that could be used as an alternative, but there would be no forum.

> 3/ Or you can prefer a NAEV-specific hosting account. I can still propose Ouvaton. It's a French cooperative company ("hosted-hosters") with a strong link to everything open-source and free. Base hosting is around 30€/year so it won't ruin us. Opening an account is simple, I could do it for us and even finance it. If we choose Ouvaton, I'll pass on the login/pwd to at least 2 other admins, so we are 3 able to get into the hosting account, to eliminate any risk of SPOF.

That could also be an option. I wouldn't have a problem paying for it, but I probably won't be able to maintain too much due to time constraints.

> maybe we should use the wayback machine and copy the few ideas and still working wiki articles to another forum and/or direct it to a new site like the one before.

I have activated the wiki on github, so it should be possible to migrate here. At the current time, anybody should be able to edit the wiki.

**Comment by jostephd** [comment] 2019-09-07 06:06
> I have activated the wiki on github, so it should be possible to migrate here. At the current time, anybody should be able to edit the wiki.

The problem with github wikis is that they don't accept pull requests, so you've to choose between letting anyone edit (and cleaning up spam) and letting only people with push access edit (but then it's cumbersome to accept patches for the wiki - although, googling just now, there seems to be [a workaround](https://www.growingwiththeweb.com/2016/07/enabling-pull-requests-on-github-wikis.html)).

And by the way, _have_ you guys got control of DNS? If not you may have to register a new domain name (if you want a domain).

**Comment by Deiz** [comment] 2019-09-18 22:43
Well... this is what I get for routing Naev emails somewhere other than my primary Github email two jobs ago. Just happened to see this in my Github notifications.

The short version is that the original naev.org host was compromised due to an outdated Wordpress install, with malicious code injected into virtually every PHP file below the web root. I allowed the hosting provider to axe the host after that, since it also got naev.org marked as a malicious site.

I had regular backups including the forum, blog, and wiki DBs plus all the web assets running on an old desktop, and we should be able to bring the Naev site back. That desktop's boot disk died a few months ago but the backups are on a perfectly-healthy RAID5. I can spend some time getting the backups off that machine this weekend or next, at which point it should be feasible to get everything back up and running if someone's willing to host it.

**Comment by ids1024** [comment] 2019-09-18 23:13
@Deiz Great! For reference, do you happen to know how much space all the files and databases take up? I assume the site got little enough traffic that the bandwidth and processing requirements are fairly minimal.

I can probably help set things up in some capacity. Though without paying more, the $5/month VPS I currently have is already at it's limit; so I don't personally have spare hosting to offer, except for something small like [API docs](https://naevdocs.ids1024.com/).

Perhaps it would be desirable to set up some kind of hosting more than one person has access to, to help in this sort of situation (which is common enough)? I'm not sure what the best option for that is.

**Comment by smeagolthellama** [comment] 2019-11-04 08:46
Is the website still down? Firefox is giving me a "server not found". I'm not sure though, because I can't access some other sites that I think are up.

**Comment by duckinator** [comment] 2019-12-10 07:41
I've not played the Naev, I just happened to run into this while looking up space-related games.

However, if someone can get me some nice screenshots showing off the game, I'd be happy to take them and toss together a quick page (basing the description off stuff from the README + Steam page) and put together a simple homepage that can be tossed on GitHub pages.

Then if DNS were pointed at it, there would at least be a homepage, and it'd have the bonuses of the hosting being free and being significantly more robust against being hacked (since it'd just be static content). :slightly_smiling_face: 

@Deiz what're your thoughts on that?^

**Comment by duckinator** [comment] 2019-12-10 07:50
It also looks like at least some of the wiki is available on archive.org, so that could potentially be moved to the GitHub Wiki for this repository. It may be out of date, but would likely provide a solid starting point.

You could also, potentially, toss a very basic server somewhere (I would be happy to write this as well, and you could toss it on a free heroku instance or something) that just redirects `wiki.naev.org/<blah>` to `https://github.com/naev/naev/wiki/<blah>` and it'd be close to a drop-in replacement for the old one.

**Comment by bobbens** [comment] 2020-01-01 00:08
OK, I have redone the website with a static website generator. The git repo is at https://github.com/naev/naev-website . It has the blarg, about, media, and download tabs, but it is easy to add more. I will be hosting it on one of my university servers. For security reasons I will only be hosting static html. A bonus thing about the server is that it should be possible to self-host binaries and ndata instead of relying on sourceforge.

Regarding the naev.org, I tried to register it today, but it seems to be taken until February. We'll have to wait until it expires unless anyone knows anything about that.

**Comment by fiendish** [comment] 2020-01-01 00:38
> I will be hosting it on one of my university servers

If it's a static site, why not let github host it?

**Comment by bobbens** [comment] 2020-01-01 00:46
> > I will be hosting it on one of my university servers
> 
> If it's a static site, why not let github host it?

That's a good point. It's now live at https://naev.github.io/ . I haven't really put together a proper update script, but it should be possible to handle the updating more seamlessly.

**Comment by bobbens** [comment] 2020-01-01 01:12
> Regarding the naev.org, I tried to register it today, but it seems to be taken until February. We'll have to wait until it expires unless anyone knows anything about that.

I have gotten around to starting the domain name transfer process. If all goes well in a few days we'll have naev.org and stuff up and running.

**Comment by bobbens** [comment] 2020-01-06 04:27
It's up. All systems go! I have also manually transferred some of the wiki pages to github, but since I'm still hoping @Deiz can get a backup up or something, I'll leave this open.

**Comment by onpon4** [comment] 2020-01-06 04:44
Any plans to get the API docs back on there too?

**Comment by bobbens** [comment] 2020-01-19 12:29
> Any plans to get the Lua API docs back on there too?

http://api.naev.org/ is up, but it's on @ids1024 's server, while http://naev.org is using github pages.

**Comment by fiendish** [comment] 2020-02-24 20:46
I believe that github pages supports ssl via checkbox. Can you activate that please?

**Comment by bobbens** [comment] 2020-02-25 09:57
> I believe that github pages supports ssl via checkbox. Can you activate the "Enforce HTTPS" option please?
I thought I had it set on, but it wasn't so I checked it again. However, currently it is giving an invalid certificate warning (github.org certificate vs naev.org).

**Comment by bobbens** [comment] 2020-06-17 00:05
Seems to be working, closing.

**Closed by bobbens** 2020-06-17 00:05 UTC
Labels: Priority-Critical
