### ISSUE TITLE
Unable to create OpenGL context!

### ISSUE THREAD

**Issue by exa18** [naev/naev#1705] opened 2021-02-20 20:30 UTC
Naev v0.8.2+dev (linux-x86_64)
AppImage detected. Running from: /tmp/.mount_naev-0b4XbMX

ERROR ../source/src/opengl.c:376 [gl_createWindow]: Unable to create OpenGL context! Could not create GL context: GLXBadFBConfig

As for now I did running version 0.7.0 on Ubuntu 20.04 LTS.

**Comment by UncombedCoconut** [comment] 2021-02-20 20:52
Hi! If your hardware is unable to support OpenGL 3.1, can you please leave a "me too" on that issue? https://github.com/naev/naev/issues/1588

I'm not sure what else would cause the issue. The output of `glxinfo` on your machine might help us figure it out. (That command should be part of the `mesa-utils` package on Ubuntu, if it's not already available.)

**Comment by exa18** [comment] 2021-02-21 00:05
Ow. I did hope it is still support for 2.1. 
[glxinfo.txt](https://github.com/naev/naev/files/6016892/glxinfo.txt)

**Comment by UncombedCoconut** [comment] 2021-02-21 05:36
Thanks, will treat this as a duplicate of #1588 (and make sure that one reflects that you're affected too).

**Closed by UncombedCoconut** 2021-02-21 05:36 UTC
