### ISSUE TITLE
Some ignored translations

### ISSUE THREAD

**Issue by Wuzzy2** [naev/naev#1648] opened 2021-01-08 18:53 UTC
So I have started testing the translation recently and checked if everything works out so far. I have found a few strings for which the translation appears to be ignored.
I have not done heavy testing yet, but this is what I found:

- “Core Systems” is sometimes not translated in a few equipment tooltips. Strangely, sometimes it does seem to be translated (I have found no logic behind this)
- “Planetary class: %s” is never translated (in the system map)
- “Shade & Sunshine Station” (incl. description)
- “S&K Superheavy Combat Plating” (and all other S&K equipment, incl. description)

(note: all these strings have a translation in the PO files)

For the last two, I have a guess: It's because of the ampersand. In the PO files, the ampersand in “Shade & Sunshine” becomes “&amp;”

I don't know if there are more problematic strings, probably more testing is required. If you found more problematic strings, please post.

**Comment by Wuzzy2** [comment] 2021-01-08 18:54
Argh!

I meant to say: “In the PO files, the ampersand in “Shade & Sunshine” becomes “`&amp;`”.

**Comment by UncombedCoconut** [comment] 2021-01-08 19:42
Good catch, the PO files should say `&` instead of `&amp;`. (Of course, it was already wrong in the templates we generated. The root cause is our ITS rules.) Assuming you're not actively editing de.po, I'll fix the po files in bulk after correcting this.

I will update when that's done and I've looked at the other cases.

**Comment by UncombedCoconut** [comment] 2021-01-08 21:44
I have good news and bad news.
Bad news: Strings like "Core Systems (Engine)" will need to be translated. They were incorrectly omitted from naev.pot.
Good news: The other ones should be fixed.

**Comment by bobbens** [comment] 2021-01-10 14:17
> I have good news and bad news.
> Bad news: Strings like "Core Systems (Engine)" will need to be translated. They were incorrectly omitted from naev.pot.
> Good news: The other ones should be fixed.

Is this closed then?

**Comment by UncombedCoconut** [comment] 2021-01-10 14:30
From a developer perspective, this is closable.
From a user perspective, there's still English text where we should show German text.
I think the user perspective is better. We can close when there's a po update and (if the 0.8.x branch is open) I've also applied it to 0.8.x.

**Comment by UncombedCoconut** [comment] 2021-01-22 04:13
Changed my mind about closing this -- now that Weblate is working well, Weblate is the better tracker for any strings that need attention.

**Closed by UncombedCoconut** 2021-01-22 04:13 UTC
Labels: Priority-Low, Type-Defect
